//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace gtxh_m.com.gtxh.news {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewsSoap", Namespace="http://tempuri.org/")]
    public partial class News : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHotNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYanjiuNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGangWeiNewsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public News() {
            this.Url = global::gtxh_m.Properties.Settings.Default.gtxh_m_com_gtxh_news_News;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotNewsCompletedEventHandler GetHotNewsCompleted;
        
        /// <remarks/>
        public event GetIndexNewsCompletedEventHandler GetIndexNewsCompleted;
        
        /// <remarks/>
        public event GetYanjiuNewsCompletedEventHandler GetYanjiuNewsCompleted;
        
        /// <remarks/>
        public event GetGangWeiNewsCompletedEventHandler GetGangWeiNewsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHotNews", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHotNews(string key) {
            object[] results = this.Invoke("GetHotNews", new object[] {
                        key});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotNewsAsync(string key) {
            this.GetHotNewsAsync(key, null);
        }
        
        /// <remarks/>
        public void GetHotNewsAsync(string key, object userState) {
            if ((this.GetHotNewsOperationCompleted == null)) {
                this.GetHotNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotNewsOperationCompleted);
            }
            this.InvokeAsync("GetHotNews", new object[] {
                        key}, this.GetHotNewsOperationCompleted, userState);
        }
        
        private void OnGetHotNewsOperationCompleted(object arg) {
            if ((this.GetHotNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotNewsCompleted(this, new GetHotNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIndexNews", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetIndexNews(string key) {
            object[] results = this.Invoke("GetIndexNews", new object[] {
                        key});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexNewsAsync(string key) {
            this.GetIndexNewsAsync(key, null);
        }
        
        /// <remarks/>
        public void GetIndexNewsAsync(string key, object userState) {
            if ((this.GetIndexNewsOperationCompleted == null)) {
                this.GetIndexNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexNewsOperationCompleted);
            }
            this.InvokeAsync("GetIndexNews", new object[] {
                        key}, this.GetIndexNewsOperationCompleted, userState);
        }
        
        private void OnGetIndexNewsOperationCompleted(object arg) {
            if ((this.GetIndexNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexNewsCompleted(this, new GetIndexNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetYanjiuNews", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetYanjiuNews(string key, int count) {
            object[] results = this.Invoke("GetYanjiuNews", new object[] {
                        key,
                        count});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetYanjiuNewsAsync(string key, int count) {
            this.GetYanjiuNewsAsync(key, count, null);
        }
        
        /// <remarks/>
        public void GetYanjiuNewsAsync(string key, int count, object userState) {
            if ((this.GetYanjiuNewsOperationCompleted == null)) {
                this.GetYanjiuNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYanjiuNewsOperationCompleted);
            }
            this.InvokeAsync("GetYanjiuNews", new object[] {
                        key,
                        count}, this.GetYanjiuNewsOperationCompleted, userState);
        }
        
        private void OnGetYanjiuNewsOperationCompleted(object arg) {
            if ((this.GetYanjiuNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYanjiuNewsCompleted(this, new GetYanjiuNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGangWeiNews", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetGangWeiNews(string key, int pageIndex, int pageSize) {
            object[] results = this.Invoke("GetGangWeiNews", new object[] {
                        key,
                        pageIndex,
                        pageSize});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetGangWeiNewsAsync(string key, int pageIndex, int pageSize) {
            this.GetGangWeiNewsAsync(key, pageIndex, pageSize, null);
        }
        
        /// <remarks/>
        public void GetGangWeiNewsAsync(string key, int pageIndex, int pageSize, object userState) {
            if ((this.GetGangWeiNewsOperationCompleted == null)) {
                this.GetGangWeiNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGangWeiNewsOperationCompleted);
            }
            this.InvokeAsync("GetGangWeiNews", new object[] {
                        key,
                        pageIndex,
                        pageSize}, this.GetGangWeiNewsOperationCompleted, userState);
        }
        
        private void OnGetGangWeiNewsOperationCompleted(object arg) {
            if ((this.GetGangWeiNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGangWeiNewsCompleted(this, new GetGangWeiNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetHotNewsCompletedEventHandler(object sender, GetHotNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetIndexNewsCompletedEventHandler(object sender, GetIndexNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetYanjiuNewsCompletedEventHandler(object sender, GetYanjiuNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYanjiuNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYanjiuNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGangWeiNewsCompletedEventHandler(object sender, GetGangWeiNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGangWeiNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGangWeiNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591