<%@ Page Language="C#" AutoEventWireup="true" CodeFile="CampusTreeManage.aspx.cs"
    Inherits="Module_CampusManager_CampusTreeManage" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>基本信息管理</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <center>
            <table style="width: 100%">
                <tr>
                    <td style="width: 30%; border-right: 1px solid gray; vertical-align: top;text-align:left;">
                        <asp:TreeView ID="treeCampus" runat="server" ImageSet="Simple" BorderColor="#C3C3C3"
                            BorderStyle="Solid" BorderWidth="0px" ExpandDepth="0" NodeIndent="30" 
                            ShowLines="True" AutoGenerateDataBindings="False">
                            <NodeStyle Font-Names="verdana" Font-Size="15pt" ForeColor="#3366FF" HorizontalPadding="0px"
                                NodeSpacing="0px" VerticalPadding="0px" />
                            <ParentNodeStyle Font-Bold="False" />
                            <SelectedNodeStyle Font-Underline="True" ForeColor="#FF6600" HorizontalPadding="0px"
                                VerticalPadding="0px" />
                        </asp:TreeView>
                    </td>
                    <td style="vertical-align: middle; height: 400px">
                        <iframe name="framedetail" src="../../Common/open.aspx" scrolling="auto" frameborder="0" width="100%" height="100%" allowtransparency="true">
                        </iframe>
                    </td>
                </tr>
            </table>
        </center>
    </div>
    <%-- <a href="CampusTableManage.aspx" style="display: block; position: absolute; bottom: 10px;
        left: 10px; height: 20px; width: 70px; text-decoration: none; background-color: #55cc55">
        表格形式</a>--%>
    </form>
</body>
</html>
