//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace gtxh_m.com.gtxh.fxs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ArticleSoap", Namespace="http://tempuri.org/")]
    public partial class Article : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTopArticleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArticleListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArticleList_FreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback PayArticleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Article() {
            this.Url = global::gtxh_m.Properties.Settings.Default.gtxh_m_com_gtxh_fxs_Article;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTopArticleCompletedEventHandler GetTopArticleCompleted;
        
        /// <remarks/>
        public event GetArticleListCompletedEventHandler GetArticleListCompleted;
        
        /// <remarks/>
        public event GetArticleList_FreeCompletedEventHandler GetArticleList_FreeCompleted;
        
        /// <remarks/>
        public event IsPayCompletedEventHandler IsPayCompleted;
        
        /// <remarks/>
        public event PayArticleCompletedEventHandler PayArticleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTopArticle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTopArticle(string key, int topCount) {
            object[] results = this.Invoke("GetTopArticle", new object[] {
                        key,
                        topCount});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopArticleAsync(string key, int topCount) {
            this.GetTopArticleAsync(key, topCount, null);
        }
        
        /// <remarks/>
        public void GetTopArticleAsync(string key, int topCount, object userState) {
            if ((this.GetTopArticleOperationCompleted == null)) {
                this.GetTopArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopArticleOperationCompleted);
            }
            this.InvokeAsync("GetTopArticle", new object[] {
                        key,
                        topCount}, this.GetTopArticleOperationCompleted, userState);
        }
        
        private void OnGetTopArticleOperationCompleted(object arg) {
            if ((this.GetTopArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopArticleCompleted(this, new GetTopArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetArticleList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetArticleList(string key, int pageIndex, int pageSize) {
            object[] results = this.Invoke("GetArticleList", new object[] {
                        key,
                        pageIndex,
                        pageSize});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetArticleListAsync(string key, int pageIndex, int pageSize) {
            this.GetArticleListAsync(key, pageIndex, pageSize, null);
        }
        
        /// <remarks/>
        public void GetArticleListAsync(string key, int pageIndex, int pageSize, object userState) {
            if ((this.GetArticleListOperationCompleted == null)) {
                this.GetArticleListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArticleListOperationCompleted);
            }
            this.InvokeAsync("GetArticleList", new object[] {
                        key,
                        pageIndex,
                        pageSize}, this.GetArticleListOperationCompleted, userState);
        }
        
        private void OnGetArticleListOperationCompleted(object arg) {
            if ((this.GetArticleListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArticleListCompleted(this, new GetArticleListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetArticleList_Free", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetArticleList_Free(string key, int pageIndex, int pageSize) {
            object[] results = this.Invoke("GetArticleList_Free", new object[] {
                        key,
                        pageIndex,
                        pageSize});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetArticleList_FreeAsync(string key, int pageIndex, int pageSize) {
            this.GetArticleList_FreeAsync(key, pageIndex, pageSize, null);
        }
        
        /// <remarks/>
        public void GetArticleList_FreeAsync(string key, int pageIndex, int pageSize, object userState) {
            if ((this.GetArticleList_FreeOperationCompleted == null)) {
                this.GetArticleList_FreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArticleList_FreeOperationCompleted);
            }
            this.InvokeAsync("GetArticleList_Free", new object[] {
                        key,
                        pageIndex,
                        pageSize}, this.GetArticleList_FreeOperationCompleted, userState);
        }
        
        private void OnGetArticleList_FreeOperationCompleted(object arg) {
            if ((this.GetArticleList_FreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArticleList_FreeCompleted(this, new GetArticleList_FreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsPay(int logininfoId, int articleId) {
            object[] results = this.Invoke("IsPay", new object[] {
                        logininfoId,
                        articleId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsPayAsync(int logininfoId, int articleId) {
            this.IsPayAsync(logininfoId, articleId, null);
        }
        
        /// <remarks/>
        public void IsPayAsync(int logininfoId, int articleId, object userState) {
            if ((this.IsPayOperationCompleted == null)) {
                this.IsPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPayOperationCompleted);
            }
            this.InvokeAsync("IsPay", new object[] {
                        logininfoId,
                        articleId}, this.IsPayOperationCompleted, userState);
        }
        
        private void OnIsPayOperationCompleted(object arg) {
            if ((this.IsPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPayCompleted(this, new IsPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PayArticle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PayArticle(int logininfoId, int articleId) {
            object[] results = this.Invoke("PayArticle", new object[] {
                        logininfoId,
                        articleId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PayArticleAsync(int logininfoId, int articleId) {
            this.PayArticleAsync(logininfoId, articleId, null);
        }
        
        /// <remarks/>
        public void PayArticleAsync(int logininfoId, int articleId, object userState) {
            if ((this.PayArticleOperationCompleted == null)) {
                this.PayArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPayArticleOperationCompleted);
            }
            this.InvokeAsync("PayArticle", new object[] {
                        logininfoId,
                        articleId}, this.PayArticleOperationCompleted, userState);
        }
        
        private void OnPayArticleOperationCompleted(object arg) {
            if ((this.PayArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PayArticleCompleted(this, new PayArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTopArticleCompletedEventHandler(object sender, GetTopArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetArticleListCompletedEventHandler(object sender, GetArticleListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArticleListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArticleListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetArticleList_FreeCompletedEventHandler(object sender, GetArticleList_FreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArticleList_FreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArticleList_FreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void IsPayCompletedEventHandler(object sender, IsPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PayArticleCompletedEventHandler(object sender, PayArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PayArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591